cd zombies
start python zombie1.py
start python zombie2.py
start python zombie3.py
start python zombie4.py
start python zombie5.py
start python zombie6.py
start python zombie7.py
start python zombie8.py
start python zombie9.py
start python zombie10.py
start python zombie11.py
start python zombie12.py
start python zombie13.py
start python zombie14.py
start python zombie15.py
start python zombie16.py
start python zombie17.py
start python zombie18.py
start python zombie19.py
start python zombie20.py
start python zombie21.py
start python zombie22.py
start python zombie23.py
start python zombie24.py
start python zombie25.py
start python zombie26.py
start python zombie27.py
start python zombie28.py
start python zombie29.py
start python zombie30.py
start python zombie31.py
start python zombie32.py
start python zombie33.py
start python zombie34.py
start python zombie35.py
start python zombie36.py
start python zombie37.py
start python zombie38.py
start python zombie39.py
start python zombie40.py
start python zombie41.py
start python zombie42.py
start python zombie43.py
start python zombie44.py
start python zombie45.py
start python zombie46.py
start python zombie47.py
start python zombie48.py
start python zombie49.py
start python zombie50.py
